[ADD] estate: Create custom views T#72976
gerashdo/odoo-gettingstarted pull request #3
Opened 2023-06-26 18:54 UTC by gerashdo

Chapter 7

- Create custom list view with specific fields to display.
- Create custom form view with custom layout and fields organization.
- Create search view with custom filter and group by options.

Exercises reference link:
https://www.odoo.com/documentation/16.0/developer/tutorials/getting_started/07_basicviews.html#

2023-06-26 22:57 UTC, gerashdo commented
Ready for review @JesusValdez96 🙂.

2023-06-26 23:35 UTC, JesusValdez96 requested changes
Good job @gerashdo only run pre-commit and it's done.

I forgot to tell you that you can install these useful extensions:

- eamodio.gitlens
- ms-python.pylint
- dotjoshjohnson.xml
- ms-python.python
-  ms-python.vscode-pylance
-  ms-python.flake8
- dbaeumer.vscode-eslint
-  redhat.vscode-xml
- shardulm94.trailing-spaces

2023-06-26 23:35 UTC, JesusValdez96 commented on estate/models/estate_property_type.py
> +
Did you run pre-commit? 

Add a blank line at the end of file.

2023-06-26 23:35 UTC, JesusValdez96 commented on estate/views/estate_property_type_views.xml
> +<?xml version='1.0' encoding='utf-8'?>
```suggestion
<?xml version='1.0' encoding='utf-8' ?>
```

2023-06-26 23:35 UTC, JesusValdez96 commented on estate/views/estate_property_type_views.xml
> +    </record>
This will be autofixed by `pre-commit-vauxoo -t all`

```suggestion
    </record>
```

2023-06-27 14:08 UTC, gerashdo commented on estate/models/estate_property_type.py
> +
I remember that I did, but surly I did not 😅.
Thank you!

2023-06-27 14:28 UTC, gerashdo commented
@JesusValdez96  I am not sure what is happening here.
I run pre-commit, and it leaves a blank line, if I run it again everything is correct but, when I push the changes the blank line is not in the remote repository.

**Local**
![image](https://github.com/gerashdo/odoo-gettingstarted/assets/55073086/70232026-3fba-43b0-8416-7275de9219c7)

**Remote**
![image](https://github.com/gerashdo/odoo-gettingstarted/assets/55073086/8d18e40c-0d8d-430f-858c-6856c27dc796)

2023-06-27 17:03 UTC, JesusValdez96 commented
@gerashdo in remote it's ok, when there is no new line at the end, you will see an icon like this
![newline](https://github.com/gerashdo/odoo-gettingstarted/assets/108701886/43e6407a-5829-4e79-a160-f6c7615e6609)

2023-06-27 17:57 UTC, JesusValdez96 approved these changes

2023-06-27 18:27 UTC, gerashdo commented
Can it be merged now, or there are pending changes? @JesusValdez96

2023-06-27 18:56 UTC, merged